School/Controllers/DqworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;
using Webdiyer;
using Webdiyer.WebControls.Mvc;
namespace School.Controllers
{
    public class DqworkController : Controller
    {
        //
        // GET: /dqwork/
        private school2014Entities xx = new school2014Entities();
        public PartialViewResult _Index1(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "理论学习").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index2(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "组织机构").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index3(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "制度建设").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index4(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "党群动态").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index5(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "学院党校").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index6(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "党支部风采").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index7(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "党员风采").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index8(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "党员工作站").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index9(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "工会教代会").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index10(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "妇委会").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public ActionResult Detials(int id)
        {
            var mes = xx.dqwork.Single(x => x.ID == id);
            return View(mes);
        }
    }
}

School/Controllers/NoticeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;
using System.Data.Entity;
using System.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Security;
using System.Web.SessionState;
using Webdiyer;
using Webdiyer.WebControls.Mvc;
namespace School.Controllers
{
    public class NoticeController : Controller
    {
        //
        // GET: /NoticesList/
        private school2014Entities a = new school2014Entities();
        public ViewResult Index(int Notice = 1)
        {
            PagedList<NoticesSet> model = a.Notices.OrderByDescending(x => x.Date).ToPagedList(Notice, 12);

            return View(model);
        }
        public ViewResult Details(int id)
        {
            NoticesSet Notice = a.Notices.Single(m => m.ID == id);
            return View(Notice);
        }

    }
}

School/Controllers/ScienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;
using Webdiyer;
using Webdiyer.WebControls.Mvc;
namespace School.Controllers
{
    public class ScienceController : Controller
    {
        //
        // GET: /science/
        private school2014Entities tt = new school2014Entities();
        public PartialViewResult _Index1(int ScienceIndex = 1)
        {
            PagedList<scienceSet> sub = tt.science.OrderByDescending(x => x.time).Where(x => x.kind == "科研机构").ToPagedList(ScienceIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index2(int ScienceIndex = 1)
        {
            PagedList<scienceSet> sub = tt.science.OrderByDescending(x => x.time).Where(x => x.kind == "科研通知").ToPagedList(ScienceIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index3(int ScienceIndex = 1)
        {
            PagedList<scienceSet> sub = tt.science.OrderByDescending(x => x.time).Where(x => x.kind == "科研成果").ToPagedList(ScienceIndex, 7);
            return PartialView(sub);
        }
        public ActionResult Details(int id)
        {
            var mes = tt.science.Single(x => x.ID == id);
            return View(mes);
        }
    }
}

School/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;

namespace School.Controllers
{
    public class SubjectController : Controller
    {
        //
        // GET: /Subject/
        private school2014Entities aa = new school2014Entities();
        public PartialViewResult _Index1(int SunIndex = 1)
        {
            List<SubjectSet> sub = aa.Subject.OrderByDescending(x => x.time).Where(x=>x.kind=="办学体系").Take(7).ToList();
            return PartialView(sub);
        }   
        public PartialViewResult _Index2(int SunIndex = 1)
        {
            List<SubjectSet> sub = aa.Subject.OrderByDescending(x => x.time).Where(x => x.kind == "学科设置").Take(7).ToList();
            return PartialView(sub);
        }
        public PartialViewResult _Index3(int SunIndex = 1)
        {
            List<SubjectSet> sub = aa.Subject.OrderByDescending(x => x.time).Where(x => x.kind == "硕士点").Take(7).ToList();
            return PartialView(sub);
        }
        public PartialViewResult _Index4(int SunIndex = 1)
        {
            List<SubjectSet> sub = aa.Subject.OrderByDescending(x => x.time).Where(x => x.kind == "学术交流").Take(7).ToList();
            return PartialView(sub);
        }
        public ActionResult Details(int id)
        {
            var mes = aa.Subject.Single(x => x.ID == id);
            return View(mes);
        }

    }
}

School/Controllers/xueshuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;
using System.Data.Entity;
using System.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Security;
using System.Web.SessionState;
using Webdiyer;
using Webdiyer.WebControls.Mvc;
namespace School.Controllers
{
    public class xueshuController : Controller
    {
        //
        // GET: /NoticesList/
        private school2014Entities aa = new school2014Entities();
        public ViewResult Index(int Notice = 1)
        {
            PagedList<ActivitySet> model = aa.Activity.OrderByDescending(x => x.Date).ToPagedList(Notice, 12);

            return View(model);
        }
        public ViewResult Details(int id)
        {
            ActivitySet Notice = aa.Activity.Single(m => m.ID == id);
            return View(Notice);
        }

    }
}

School/Views/xueshu/Details.cshtml
@model School.Models.ActivitySet

@{
    ViewBag.Title = "学术活动";
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>艺术与设计学院</title>
    <link rel="shortcut icon" href="" type="image/x-icon" />
    <link rel="stylesheet" href="../../css/base.css"/>
    <link rel="stylesheet" href="../../css/pc/common.css" />
    <link rel="stylesheet" href="../../css/pc/dqgongzuo.css" />
    <link rel="stylesheet" href="../../css/pc/xueyuanxinwen.css" />
    <script src="../../content/js/seajs/sea.js" data-main="modules/school_intro"></script>
</head>
<body>
    <div class="nav">
        <a href="@Url.Action("Index","Home")"><img src="../../content/images/rCollegeLg.jpg" alt ="logo" class="fl" id="logo"/></a>
        <ul class="firstNav">
                    <li ><a href="@Url.Action("school_intro","Home")">学院概况</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("school_intro","Home")">学院简介</a></li>
                            <li><a href="@Url.Action("school_history","Home")">历史沿革</a></li>
                            <li><a href="@Url.Action("school_nowleader","Home")">现任领导</a></li>
                            <li><a href="">系所机构</a></li>
                            <li><a href="">学院方位图</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("_TeaList1","TeaTeam")">师资队伍</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_TeaList1","TeaTeam")">艺术设计</a></li>
                            <li><a href="@Url.Action("_TeaList2", "TeaTeam")">工业设计</a></li>
                            <li><a href="@Url.Action("_TeaList2", "TeaTeam")">音乐系</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Subject")">学科建设</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1","Subject")">办学体系</a></li>
                            <li><a href="@Url.Action("_Index2","Subject")">学科设置</a></li>
                            <li><a href="@Url.Action("_Index3","Subject")">硕士点</a></li>
                            <li><a href="@Url.Action("_Index4","Subject")">学术交流</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","zhuanye")">专业建设</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1","zhuanye")">教学团队</a></li>
                            <li><a href="@Url.Action("_Index2","zhuanye")">专业介绍</a></li>
                            <li><a href="@Url.Action("_Index3","zhuanye")">培养方案</a></li>
                            <li><a href="@Url.Action("_Index4","zhuanye")">特色专业</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Jwguanli")">教务管理</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1","Jwguanli")">制度文件</a></li>
                            <li><a href="@Url.Action("_Index2","Jwguanli")">教务通知</a></li>
                            <li><a href="@Url.Action("_Index3","Jwguanli")">实践教学</a></li>
                            <li><a href="@Url.Action("_Index4","Jwguanli")">工作流程</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Science")">科学研究</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1","Science")">科研机构</a></li>
                            <li><a href="@Url.Action("_Index2","Science")">科研通知</a></li>
                            <li><a href="@Url.Action("_Index3","Science")">科研成果</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Dqwork")">党群工作</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1", "Dqwork")">理论学习</a></li>
                            <li><a href="@Url.Action("_Index2","Dqwork")">组织机构</a></li>
                            <li><a href="@Url.Action("_Index3", "Dqwork")">制度建设</a></li>
                            <li><a href="@Url.Action("_Index4", "Dqwork")">党群动态</a></li>
                            <li><a href="@Url.Action("_Index5", "Dqwork")">学院党校</a></li>
                            <li><a href="@Url.Action("_Index6", "Dqwork")">党支部风采</a></li>
                            <li><a href="@Url.Action("_Index7", "Dqwork")">党员风采</a></li>
                            <li><a href="@Url.Action("_Index8", "Dqwork")">党员工作站</a></li>
                            <li><a href="@Url.Action("_Index9", "Dqwork")">工会教代会</a></li>
                            <li><a href="@Url.Action("_Index10", "Dqwork")">妇委会</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Txwork")">团学工作</a>
                        <ul class="secondNav">
                    <li><a href="@Url.Action("_Index1","Txwork")">思想教育</a></li>
                    <li><a href="@Url.Action("_Index2", "Txwork")">学风建设</a></li>
                    <li><a href="@Url.Action("_Index3", "Txwork")">日常管理</a></li>
                    <li><a href="@Url.Action("_Index4", "Txwork")">奖励工作</a></li>
                    <li><a href="@Url.Action("_Index5", "Txwork")">团学活动</a></li>
                    <li><a href="@Url.Action("_Index6", "Txwork")">就业工作</a></li>
                    <li><a href="@Url.Action("_Index7", "Txwork")">健康教育</a></li>
                    <li><a href="@Url.Action("_Index8", "Txwork")">创新创业</a></li>
                    <li><a href="@Url.Action("_Index9", "Txwork")">岁月答疑</a></li>
                </ul>

                    </li>
                    <li><a href="@Url.Action("Index","yyfc")">艺苑风采</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("Index","yyfc")">学院风采</a></li>
                            <li><a href="@Url.Action("Index2","yyfc")">校园电子报</a></li>
                        </ul>

                    </li>
                    <li class="last"><a href="@Url.Action("Index","zhuanti")">专题</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("Index","zhuanti")">党的群众路线</a></li>
                        </ul>

                    </li>

                </ul>
        <form action="" method="" class="fr search">
            <input type="text" name="" class="fl"/>
            <input type="image" src="../../content/images/search.png " class="fl">
        </form>
    </div>
    <div class="header">
        <div class="bg"></div>
    </div>

    <div class="content ">
        <div class="conhead">
                <img src="../../content/images/bantou.png" class="bantou">
                <form class="btform">
                        <input type="text" size="14">
                        <input type="submit" value="搜索" class="btsub">
                </form>
                <a href="@Url.Action("Index","NewsList")" class="flor">学院新闻</a>
                <div class="flor btline"></div>
                <a href="@Url.Action("Index","Notice")" class="flor">通知公告</a>
        </div>

        <div class="center" style="background:white">
                <div class="bant">
                        <span class="banth">@Model.Title</span>
                        <p>&nbsp&nbsp&nbsp&nbsp&nbsp消息出自：<span>艺术学院</span>&nbsp&nbsp&nbsp&nbsp &nbsp&nbsp<span class="spspan">@Model.Date</span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</p>
                </div>
                <div class="cencont">
                        <p>@Html.Raw(@Model.Content)</p> 
                        
                </div>
        </div>
        <div class="footer">
            <center>版权所有：中国矿业大学艺术与设计学院 <a href="@Url.Action("LogOn", "Account", new { area = "Admin" })">管理员登录</a> </center>
            <center>地址：江苏省徐州市大学路1号中国矿业大学南湖校区 | 电话：0516-8359199 | 传真：0516-83591999</center>
        </div>
    </div>
</body>
</html>

School/Views/xueshu/Index.cshtml
@model PagedList<School.Models.ActivitySet>
@using Webdiyer.WebControls.Mvc
@{
    Layout = "~/Views/Shared/_ViewPage1.cshtml";
}
<div class="content ">
        <p class="title">学术活动</p>
        <div class="center">
                <ul class="center_nav fl">
                    
                </ul>
                @{
                    int k=1;
                    foreach (var item in Model)
                    {
                <div class="center_body fl">
                    <div>
                        <p>@Html.ActionLink((k++).ToString() + "." + item.Title, "Details", new { id = item.ID })</p>
                        <span>@item.Date</span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<span></span>
                    </div>
                </div>
                    }
                    }
                    <p><div style="padding:0px  auto 0px auto">
        <a> @Html.Pager(Model,
            new PagerOptions
            {
                NextPageText = "下一页",
                PrevPageText = "上一页",
                FirstPageText = "首页",
                LastPageText = "末页",
                PageIndexParameterName = "Notice",
                CssClass = "pages",
                CurrentPagerItemWrapperFormatString = "<span class=\"cpb\">{0}</span>",
                NumericPagerItemWrapperFormatString = "<span class=\"item\">{0}</span>",
                NumericPagerItemCount=6
            },
                null,
                new
                {
                    id = ViewBag.columnId,
                    classId = ViewBag.classId
                })
                </a>
         </div></p>

        </div>
        <div class="footer">
            <center>版权所有：中国矿业大学艺术与设计学院 <a href="@Url.Action("LogOn", "Account", new { area = "Admin" })"><small>后台管理</small></a> </center>
            <center>地址：江苏省徐州市大学路1号中国矿业大学南湖校区 | 电话：0516-8359199 | 传真：0516-83591999</center>
        </div>
</div>