School/Controllers/DqworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;
using Webdiyer;
using Webdiyer.WebControls.Mvc;
namespace School.Controllers
{
    public class DqworkController : Controller
    {
        //
        // GET: /dqwork/
        private school2014Entities xx = new school2014Entities();
        public PartialViewResult _Index1(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "理论学习").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index2(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "组织机构").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index3(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "制度建设").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index4(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "党群动态").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index5(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "学院党校").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index6(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "党支部风采").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index7(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "党员风采").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index8(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "党员工作站").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index9(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "工会教代会").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index10(int jwIndex = 1)
        {
            PagedList<dqworkSet> sub = xx.dqwork.OrderByDescending(x => x.time).Where(x => x.kind == "妇委会").ToPagedList(jwIndex, 7);
            return PartialView(sub);
        }
        public ActionResult Detials(int id)
        {
            var mes = xx.dqwork.Single(x => x.ID == id);
            return View(mes);
        }
    }
}

School/Controllers/JwguanliController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;
using Webdiyer;
using Webdiyer.WebControls.Mvc;
namespace School.Controllers
{
    public class JwguanliController : Controller
    {
        //
        // GET: /jwmanger/
        private school2014Entities xx = new school2014Entities();
        public PartialViewResult _Index1(int jwIndex = 1)
        {
            PagedList<jwmangerSet> sub = xx.jwmanger.OrderByDescending(x => x.time).Where(x => x.kind == "制度文件").ToPagedList(jwIndex,7);
            return PartialView(sub);
        }
        public PartialViewResult _Index2(int jwIndex = 1)
        {
            PagedList<jwmangerSet> sub = xx.jwmanger.OrderByDescending(x => x.time).Where(x => x.kind == "教务通知").ToPagedList(jwIndex,7);
            return PartialView(sub);
        }
        public PartialViewResult _Index3(int jwIndex = 1)
        {
            PagedList<jwmangerSet> sub = xx.jwmanger.OrderByDescending(x => x.time).Where(x => x.kind == "实践教学").ToPagedList(jwIndex,7);
            return PartialView(sub);
        }
        public PartialViewResult _Index4(int jwIndex = 1)
        {
            PagedList<jwmangerSet> sub = xx.jwmanger.OrderByDescending(x => x.time).Where(x => x.kind == "工作流程").ToPagedList(jwIndex,7);
            return PartialView(sub);
        }
        public ActionResult Details(int id)
        {
            var mes = xx.jwmanger.Single(x => x.ID == id);
            return View(mes);
        }
    }
}

School/Controllers/ScienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;
using Webdiyer;
using Webdiyer.WebControls.Mvc;
namespace School.Controllers
{
    public class ScienceController : Controller
    {
        //
        // GET: /science/
        private school2014Entities tt = new school2014Entities();
        public PartialViewResult _Index1(int ScienceIndex = 1)
        {
            PagedList<scienceSet> sub = tt.science.OrderByDescending(x => x.time).Where(x => x.kind == "科研机构").ToPagedList(ScienceIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index2(int ScienceIndex = 1)
        {
            PagedList<scienceSet> sub = tt.science.OrderByDescending(x => x.time).Where(x => x.kind == "科研通知").ToPagedList(ScienceIndex, 7);
            return PartialView(sub);
        }
        public PartialViewResult _Index3(int ScienceIndex = 1)
        {
            PagedList<scienceSet> sub = tt.science.OrderByDescending(x => x.time).Where(x => x.kind == "科研成果").ToPagedList(ScienceIndex, 7);
            return PartialView(sub);
        }
        public ActionResult Details(int id)
        {
            var mes = tt.science.Single(x => x.ID == id);
            return View(mes);
        }
    }
}

School/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;

namespace School.Controllers
{
    public class SubjectController : Controller
    {
        //
        // GET: /Subject/
        private school2014Entities aa = new school2014Entities();
        public PartialViewResult _Index1(int SunIndex = 1)
        {
            List<SubjectSet> sub = aa.Subject.OrderByDescending(x => x.time).Where(x=>x.kind=="办学体系").Take(7).ToList();
            return PartialView(sub);
        }   
        public PartialViewResult _Index2(int SunIndex = 1)
        {
            List<SubjectSet> sub = aa.Subject.OrderByDescending(x => x.time).Where(x => x.kind == "学科设置").Take(7).ToList();
            return PartialView(sub);
        }
        public PartialViewResult _Index3(int SunIndex = 1)
        {
            List<SubjectSet> sub = aa.Subject.OrderByDescending(x => x.time).Where(x => x.kind == "硕士点").Take(7).ToList();
            return PartialView(sub);
        }
        public PartialViewResult _Index4(int SunIndex = 1)
        {
            List<SubjectSet> sub = aa.Subject.OrderByDescending(x => x.time).Where(x => x.kind == "学术交流").Take(7).ToList();
            return PartialView(sub);
        }
        public ActionResult Details(int id)
        {
            var mes = aa.Subject.Single(x => x.ID == id);
            return View(mes);
        }

    }
}

School/Controllers/TeaTeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using School.Models;
using Webdiyer;
using Webdiyer.WebControls.Mvc;

namespace School.Controllers
    {
    public class TeaTeamController :Controller
        {
        private school2014Entities db = new school2014Entities();
        public ActionResult _TeaList1(int TeaIndex=1)
            {
            PagedList<TeaTeamSet> model = db.TeaTeam.OrderByDescending(x => x.ID).Where(x=>x.kind=="艺术设计").ToPagedList(TeaIndex,15);
            return View(model);
            }
        public ActionResult _TeaList2(int TeaIndex = 1)
        {
            PagedList<TeaTeamSet> model = db.TeaTeam.OrderByDescending(x => x.ID).Where(x => x.kind == "工业设计").ToPagedList(TeaIndex, 15);
            return View(model);
        }
        public ActionResult _TeaList3(int TeaIndex = 1)
        {
            PagedList<TeaTeamSet> model = db.TeaTeam.OrderByDescending(x => x.ID).Where(x => x.kind == "音乐系").ToPagedList(TeaIndex, 15);
            return View(model);
        }
        public ActionResult TeaDetails(int id)
        {
            TeaTeamSet model = db.TeaTeam.Single(x => x.ID == id);
            return View(model);
        }
        }
    }

School/Views/Subject/Details.cshtml
@model School.Models.SubjectSet




<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
    <title>艺术与设计学院</title>
    <link rel="shortcut icon" href="" type="image/x-icon" />
    <link rel="stylesheet" href="../../css/base.css"/>
    <link rel="stylesheet" href="../../css/pc/common.css" />
    <link rel="stylesheet" href="../../css/pc/txgongzuo2.css" />

    <script src="../content/js/seajs/sea.js" data-main="modules/school_intro"></script>
</head>
<body>
    <div class="nav">
        <a href="@Url.Action("school_intro","Home")"><img src="../../content/images/rCollegeLg.jpg"class="fl" id="logo"/></a>
        <ul class="firstNav">
                    <li ><a href="@Url.Action("school_intro","Home")">学院概况</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("school_intro","Home")">学院简介</a></li>
                            <li><a href="@Url.Action("school_history","Home")">历史沿革</a></li>
                            <li><a href="@Url.Action("school_nowleader","Home")">现任领导</a></li>
                            <li><a href="">系所机构</a></li>
                            <li><a href="">学院方位图</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("_TeaList1","TeaTeam")">师资队伍</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_TeaList1","TeaTeam")">艺术设计</a></li>
                            <li><a href="@Url.Action("_TeaList2", "TeaTeam")">工业设计</a></li>
                            <li><a href="@Url.Action("_TeaList2", "TeaTeam")">音乐系</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Subject")">学科建设</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1","Subject")">办学体系</a></li>
                            <li><a href="@Url.Action("_Index2","Subject")">学科设置</a></li>
                            <li><a href="@Url.Action("_Index3","Subject")">硕士点</a></li>
                            <li><a href="@Url.Action("_Index4","Subject")">学术交流</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","zhuanye")">专业建设</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1","zhuanye")">教学团队</a></li>
                            <li><a href="@Url.Action("_Index2","zhuanye")">专业介绍</a></li>
                            <li><a href="@Url.Action("_Index3","zhuanye")">培养方案</a></li>
                            <li><a href="@Url.Action("_Index4","zhuanye")">特色专业</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Jwguanli")">教务管理</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1","Jwguanli")">制度文件</a></li>
                            <li><a href="@Url.Action("_Index2","Jwguanli")">教务通知</a></li>
                            <li><a href="@Url.Action("_Index3","Jwguanli")">实践教学</a></li>
                            <li><a href="@Url.Action("_Index4","Jwguanli")">工作流程</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Science")">科学研究</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1","Science")">科研机构</a></li>
                            <li><a href="@Url.Action("_Index2","Science")">科研通知</a></li>
                            <li><a href="@Url.Action("_Index3","Science")">科研成果</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Dqwork")">党群工作</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("_Index1", "Dqwork")">理论学习</a></li>
                            <li><a href="@Url.Action("_Index2","Dqwork")">组织机构</a></li>
                            <li><a href="@Url.Action("_Index3", "Dqwork")">制度建设</a></li>
                            <li><a href="@Url.Action("_Index4", "Dqwork")">党群动态</a></li>
                            <li><a href="@Url.Action("_Index5", "Dqwork")">学院党校</a></li>
                            <li><a href="@Url.Action("_Index6", "Dqwork")">党支部风采</a></li>
                            <li><a href="@Url.Action("_Index7", "Dqwork")">党员风采</a></li>
                            <li><a href="@Url.Action("_Index8", "Dqwork")">党员工作站</a></li>
                            <li><a href="@Url.Action("_Index9", "Dqwork")">工会教代会</a></li>
                            <li><a href="@Url.Action("_Index10", "Dqwork")">妇委会</a></li>
                        </ul>

                    </li>
                    <li><a href="@Url.Action("_Index1","Txwork")">团学工作</a>
                        <ul class="secondNav">
                    <li><a href="@Url.Action("_Index1","Txwork")">思想教育</a></li>
                    <li><a href="@Url.Action("_Index2", "Txwork")">学风建设</a></li>
                    <li><a href="@Url.Action("_Index3", "Txwork")">日常管理</a></li>
                    <li><a href="@Url.Action("_Index4", "Txwork")">奖励工作</a></li>
                    <li><a href="@Url.Action("_Index5", "Txwork")">团学活动</a></li>
                    <li><a href="@Url.Action("_Index6", "Txwork")">就业工作</a></li>
                    <li><a href="@Url.Action("_Index7", "Txwork")">健康教育</a></li>
                    <li><a href="@Url.Action("_Index8", "Txwork")">创新创业</a></li>
                    <li><a href="@Url.Action("_Index9", "Txwork")">岁月答疑</a></li>
                </ul>

                    </li>
                    <li><a href="@Url.Action("Index","yyfc")">艺苑风采</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("Index","yyfc")">学院风采</a></li>
                            <li><a href="@Url.Action("Index2","yyfc")">校园电子报</a></li>
                        </ul>

                    </li>
                    <li class="last"><a href="@Url.Action("Index","zhuanti")">专题</a>
                        <ul class="secondNav">
                            <li><a href="@Url.Action("Index","zhuanti")">党的群众路线</a></li>
                        </ul>

                    </li>

                </ul>
        <form action="" method="" class="fr search">
            <input type="text" name="" class="fl"/>
            <input type="image" src="../content/images/search.png " class="fl">
        </form>
    </div>
    <div class="header">
        <div class="bg"></div>
    </div>

    <div class="content ">
        <p class="title">@Model.kind</p>
        <div class="center">
                <ul class="center_nav fl">
                    <li class="first"></li>

                </ul>
                <div class="center_body fl">
                    <div class="center_title">
                        @Model.title
                    </div>
                    <div class="time">
                       <span>@Model.time</span>&nbsp&nbsp消息出自：&nbsp&nbsp<span>@Model.writer</span>
                    </div>
                    <div class="detail">
                        @Html.Raw(@Model.content)
                    </div>
                </div>
                <div class="clear"></div>
        </div>
        <div class="footer">
            <center>版权所有：中国矿业大学艺术与设计学院 <a href="@Url.Action("LogOn", "Account", new { area = "Admin" })">管理员登录</a> </center>
            <center>地址：江苏省徐州市大学路1号中国矿业大学南湖校区 | 电话：0516-8359199 | 传真：0516-83591999</center>
        </div>
    </div>
</body>
</html>

School/Views/Subject/_Index1.cshtml
@model List<School.Models.SubjectSet>
@{
   Layout = "~/Views/Shared/_Index.cshtml";
}
<ul class="center-title">
    <li class="active"><a href="@Url.Action("_Index1","Subject")">办学体系</a></li>
    <li><a href="@Url.Action("_Index2","Subject")">学科设置</a></li>
    <li><a href="@Url.Action("_Index3","Subject")">硕士点</a></li>
    <li><a href="@Url.Action("_Index4","Subject")">学术交流</a></li>
</ul>
<div class="center-body">
                @foreach (var mm in Model)
                {
                @Html.Raw(@mm.content)
                }
            </div>

School/Views/Subject/_Index2.cshtml
@model List<School.Models.SubjectSet>
@{
   Layout = "~/Views/Shared/_Index.cshtml";
}
<ul class="center-title">
    <li><a href="@Url.Action("_Index1","Subject")">办学体系</a></li>
    <li class="active"><a href="@Url.Action("_Index2","Subject")">学科设置</a></li>
    <li><a href="@Url.Action("_Index3","Subject")">硕士点</a></li>
    <li><a href="@Url.Action("_Index4","Subject")">学术交流</a></li>
</ul>
<div class="center-body">
                @foreach (var mm in Model)
                {
                @Html.Raw(@mm.content)
                }
            </div>

School/Views/Subject/_Index3.cshtml
@model List<School.Models.SubjectSet>
@{
   Layout = "~/Views/Shared/_Index.cshtml";
}
<ul class="center-title">
    <li><a href="@Url.Action("_Index1","Subject")">办学体系</a></li>
    <li><a href="@Url.Action("_Index2","Subject")">学科设置</a></li>
    <li  class="active"><a href="@Url.Action("_Index3","Subject")">硕士点</a></li>
    <li><a href="@Url.Action("_Index4","Subject")">学术交流</a></li>
</ul>
<div class="center-body">
                @foreach (var mm in Model)
                {
                @Html.Raw(@mm.content)
                }
            </div>

School/Views/Subject/_Index4.cshtml
@model List<School.Models.SubjectSet>
@{
   Layout = "~/Views/Shared/_Index.cshtml";
}
<ul class="center-title">
    <li><a href="@Url.Action("_Index1","Subject")">办学体系</a></li>
    <li><a href="@Url.Action("_Index2","Subject")">学科设置</a></li>
    <li><a href="@Url.Action("_Index3","Subject")">硕士点</a></li>
    <li  class="active"><a href="@Url.Action("_Index4","Subject")">学术交流</a></li>
</ul>
<div class="center-body">
                @foreach (var mm in Model)
                {
                @Html.Raw(@mm.content)
                }
            </div>